[package]
name = "api_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustls = "0.20"
prost-types = "0.11"
prost = "0.11"
tonic = {version = "0.8", default-features = false, features = ["prost", "codegen", "tls", "tls-roots", "tls-webpki-roots"]}
serde_json = "1.0.59"
serde = { version = "1.0.125", features = ["derive"]}
anyhow = "1.0.41"
config = { version = "0.11", features = ["json"] }
lazy_static = "1.4.0"
acteur = "0.12.2"
tracing = "0.1.26"
bollard = "0.14"
futures-util = "0.3"


[build-dependencies]
tonic-build = { version = "0.8", default-features = false, features = ["prost",]}